name: 'heroku-deployment'
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BACKEND_API_URL: ${{ secrets.BACKEND_API_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Deploy to Heroku
        id: heroku
        uses: snithyanantham/docker-compose-multiple-apps-heroku-deploy@v1.0  # use the latest version of the action
        with:
          email: ${{ secrets.HEROKU_EMAIL }} # your heroku email
          api_key: ${{ secrets.HEROKU_API_KEY }} # your  heroku api key
          docker_compose_file: './docker-compose.yml' # set the path to the folder where the docker-compose file is located
          heroku_apps: '[{"imagename":"test-repo-name-31db8a65_rest_python","appname":"a7b5c0209-rest-python","apptype":"web"},{"imagename":"test-repo-name-31db8a65_frontend_react_with_rest","appname":"aca819ed7-frontend-react-with","apptype":"web"}]'